version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - /var/www/myblog:/var/work
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - /var/certbot/conf/:/etc/letsencrypt/:ro
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - app
    container_name: shop_nginx

  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
      - /var/www/myblog:/var/work
    container_name: shop_app
    depends_on:
        - db

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./db/:/var/lib/mysql/
    environment:
        MYSQL_DATABASE: shop
        MYSQL_ROOT_PASSWORD: root
    ports:
      - 8101:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: shop_db


  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
          - db
      environment:
          PMA_HOST: db
          PMA_PORT: 3306
      restart: always
      ports:
          - 8081:80
      depends_on:
          - db
      container_name: shop_pma

  certbot:
      image: certbot/certbot
      volumes:
          - ./:/var/www
          - /var/www/myblog:/var/work
          - /var/certbot/conf/:/etc/letsencrypt/
      depends_on:
          - nginx
      container_name: certbot
      command: certonly --webroot --webroot-path=/var/work/public --email serg-419@yandex.ru --agree-tos --no-eff-email -d subdomain.inshin.org
